version: '3'
services:
  ui:
    container_name: request-ui
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - proxy


  proxy:
    container_name: proxy
    build: ./proxy/
    ports:
      - '5000:5000'
